# Generated by Django 5.2.15 on 2026-07-03 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_joiner', to=settings.AUTH_USER_MODEL),
        ),
    ]
